<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInite0429b3b371cc83fc088a8e4e0a9f83b
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInite0429b3b371cc83fc088a8e4e0a9f83b', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInite0429b3b371cc83fc088a8e4e0a9f83b', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Composer\Autoload\ComposerStaticInite0429b3b371cc83fc088a8e4e0a9f83b::getInitializer($loader));

        $loader->register(true);

        return $loader;
    }
}
